package com.sofency.ticket.pojo;

import java.io.Serializable;

public class Actor  implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actor.actor_id
     *
     * @mbg.generated Wed Apr 29 18:29:03 CST 2020
     */
    private Integer actorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actor.stu_id
     *
     * @mbg.generated Wed Apr 29 18:29:03 CST 2020
     */
    private String stuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actor.activity_id
     *
     * @mbg.generated Wed Apr 29 18:29:03 CST 2020
     */
    private Integer activityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actor.name
     *
     * @mbg.generated Wed Apr 29 18:29:03 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actor.picture
     *
     * @mbg.generated Wed Apr 29 18:29:03 CST 2020
     */
    private String picture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actor.get_voted
     *
     * @mbg.generated Wed Apr 29 18:29:03 CST 2020
     */
    private Integer getVoted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actor.actor_id
     *
     * @return the value of actor.actor_id
     *
     * @mbg.generated Wed Apr 29 18:29:03 CST 2020
     */
    public Integer getActorId() {
        return actorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actor.actor_id
     *
     * @param actorId the value for actor.actor_id
     *
     * @mbg.generated Wed Apr 29 18:29:03 CST 2020
     */
    public void setActorId(Integer actorId) {
        this.actorId = actorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actor.stu_id
     *
     * @return the value of actor.stu_id
     *
     * @mbg.generated Wed Apr 29 18:29:03 CST 2020
     */
    public String getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actor.stu_id
     *
     * @param stuId the value for actor.stu_id
     *
     * @mbg.generated Wed Apr 29 18:29:03 CST 2020
     */
    public void setStuId(String stuId) {
        this.stuId = stuId == null ? null : stuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actor.activity_id
     *
     * @return the value of actor.activity_id
     *
     * @mbg.generated Wed Apr 29 18:29:03 CST 2020
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actor.activity_id
     *
     * @param activityId the value for actor.activity_id
     *
     * @mbg.generated Wed Apr 29 18:29:03 CST 2020
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actor.name
     *
     * @return the value of actor.name
     *
     * @mbg.generated Wed Apr 29 18:29:03 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actor.name
     *
     * @param name the value for actor.name
     *
     * @mbg.generated Wed Apr 29 18:29:03 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actor.picture
     *
     * @return the value of actor.picture
     *
     * @mbg.generated Wed Apr 29 18:29:03 CST 2020
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actor.picture
     *
     * @param picture the value for actor.picture
     *
     * @mbg.generated Wed Apr 29 18:29:03 CST 2020
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actor.get_voted
     *
     * @return the value of actor.get_voted
     *
     * @mbg.generated Wed Apr 29 18:29:03 CST 2020
     */
    public Integer getGetVoted() {
        return getVoted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actor.get_voted
     *
     * @param getVoted the value for actor.get_voted
     *
     * @mbg.generated Wed Apr 29 18:29:03 CST 2020
     */
    public void setGetVoted(Integer getVoted) {
        this.getVoted = getVoted;
    }
}