package com.sofency.ticket.pojo;

public class ActorKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actor.stu_id
     *
     * @mbg.generated Thu Apr 16 09:24:30 CST 2020
     */
    private String stuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actor.activity_id
     *
     * @mbg.generated Thu Apr 16 09:24:30 CST 2020
     */
    private Integer activityId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actor.stu_id
     *
     * @return the value of actor.stu_id
     *
     * @mbg.generated Thu Apr 16 09:24:30 CST 2020
     */
    public String getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actor.stu_id
     *
     * @param stuId the value for actor.stu_id
     *
     * @mbg.generated Thu Apr 16 09:24:30 CST 2020
     */
    public void setStuId(String stuId) {
        this.stuId = stuId == null ? null : stuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actor.activity_id
     *
     * @return the value of actor.activity_id
     *
     * @mbg.generated Thu Apr 16 09:24:30 CST 2020
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actor.activity_id
     *
     * @param activityId the value for actor.activity_id
     *
     * @mbg.generated Thu Apr 16 09:24:30 CST 2020
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }
}