package com.sofency.ticket.pojo;

public class Actor extends ActorKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actor.get_voted
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    private Integer getVoted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actor.name
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actor.picture
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    private String picture;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actor.get_voted
     *
     * @return the value of actor.get_voted
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    public Integer getGetVoted() {
        return getVoted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actor.get_voted
     *
     * @param getVoted the value for actor.get_voted
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    public void setGetVoted(Integer getVoted) {
        this.getVoted = getVoted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actor.name
     *
     * @return the value of actor.name
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actor.name
     *
     * @param name the value for actor.name
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actor.picture
     *
     * @return the value of actor.picture
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actor.picture
     *
     * @param picture the value for actor.picture
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }
}