package com.sofency.ticket.pojo;

import java.io.Serializable;

public class Community  implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.community_id
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    private Integer communityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.community_name
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    private String communityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.community_account
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    private String communityAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.telephone
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.invitation_code
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    private String invitationCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.password
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.community_logo
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    private String communityLogo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.community_id
     *
     * @return the value of community.community_id
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    public Integer getCommunityId() {
        return communityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.community_id
     *
     * @param communityId the value for community.community_id
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    public void setCommunityId(Integer communityId) {
        this.communityId = communityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.community_name
     *
     * @return the value of community.community_name
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    public String getCommunityName() {
        return communityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.community_name
     *
     * @param communityName the value for community.community_name
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    public void setCommunityName(String communityName) {
        this.communityName = communityName == null ? null : communityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.community_account
     *
     * @return the value of community.community_account
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    public String getCommunityAccount() {
        return communityAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.community_account
     *
     * @param communityAccount the value for community.community_account
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    public void setCommunityAccount(String communityAccount) {
        this.communityAccount = communityAccount == null ? null : communityAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.telephone
     *
     * @return the value of community.telephone
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.telephone
     *
     * @param telephone the value for community.telephone
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.invitation_code
     *
     * @return the value of community.invitation_code
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    public String getInvitationCode() {
        return invitationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.invitation_code
     *
     * @param invitationCode the value for community.invitation_code
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    public void setInvitationCode(String invitationCode) {
        this.invitationCode = invitationCode == null ? null : invitationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.password
     *
     * @return the value of community.password
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.password
     *
     * @param password the value for community.password
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.community_logo
     *
     * @return the value of community.community_logo
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    public String getCommunityLogo() {
        return communityLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.community_logo
     *
     * @param communityLogo the value for community.community_logo
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    public void setCommunityLogo(String communityLogo) {
        this.communityLogo = communityLogo == null ? null : communityLogo.trim();
    }
}