package com.sofency.ticket.pojo;

public class GrabTicketKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grabticket.grap_id
     *
     * @mbg.generated Thu Apr 16 09:24:31 CST 2020
     */
    private Integer grapId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grabticket.community_id
     *
     * @mbg.generated Thu Apr 16 09:24:31 CST 2020
     */
    private Integer communityId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grabticket.grap_id
     *
     * @return the value of grabticket.grap_id
     *
     * @mbg.generated Thu Apr 16 09:24:31 CST 2020
     */
    public Integer getGrapId() {
        return grapId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grabticket.grap_id
     *
     * @param grapId the value for grabticket.grap_id
     *
     * @mbg.generated Thu Apr 16 09:24:31 CST 2020
     */
    public void setGrapId(Integer grapId) {
        this.grapId = grapId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grabticket.community_id
     *
     * @return the value of grabticket.community_id
     *
     * @mbg.generated Thu Apr 16 09:24:31 CST 2020
     */
    public Integer getCommunityId() {
        return communityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grabticket.community_id
     *
     * @param communityId the value for grabticket.community_id
     *
     * @mbg.generated Thu Apr 16 09:24:31 CST 2020
     */
    public void setCommunityId(Integer communityId) {
        this.communityId = communityId;
    }
}