package com.sofency.ticket.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class GrabTicketExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table grabticket
     *
     * @mbg.generated Wed Apr 29 19:44:01 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table grabticket
     *
     * @mbg.generated Wed Apr 29 19:44:01 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table grabticket
     *
     * @mbg.generated Wed Apr 29 19:44:01 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grabticket
     *
     * @mbg.generated Wed Apr 29 19:44:01 CST 2020
     */
    public GrabTicketExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grabticket
     *
     * @mbg.generated Wed Apr 29 19:44:01 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grabticket
     *
     * @mbg.generated Wed Apr 29 19:44:01 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grabticket
     *
     * @mbg.generated Wed Apr 29 19:44:01 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grabticket
     *
     * @mbg.generated Wed Apr 29 19:44:01 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grabticket
     *
     * @mbg.generated Wed Apr 29 19:44:01 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grabticket
     *
     * @mbg.generated Wed Apr 29 19:44:01 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grabticket
     *
     * @mbg.generated Wed Apr 29 19:44:01 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grabticket
     *
     * @mbg.generated Wed Apr 29 19:44:01 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grabticket
     *
     * @mbg.generated Wed Apr 29 19:44:01 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grabticket
     *
     * @mbg.generated Wed Apr 29 19:44:01 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table grabticket
     *
     * @mbg.generated Wed Apr 29 19:44:01 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andGrapIdIsNull() {
            addCriterion("grap_id is null");
            return (Criteria) this;
        }

        public Criteria andGrapIdIsNotNull() {
            addCriterion("grap_id is not null");
            return (Criteria) this;
        }

        public Criteria andGrapIdEqualTo(Integer value) {
            addCriterion("grap_id =", value, "grapId");
            return (Criteria) this;
        }

        public Criteria andGrapIdNotEqualTo(Integer value) {
            addCriterion("grap_id <>", value, "grapId");
            return (Criteria) this;
        }

        public Criteria andGrapIdGreaterThan(Integer value) {
            addCriterion("grap_id >", value, "grapId");
            return (Criteria) this;
        }

        public Criteria andGrapIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("grap_id >=", value, "grapId");
            return (Criteria) this;
        }

        public Criteria andGrapIdLessThan(Integer value) {
            addCriterion("grap_id <", value, "grapId");
            return (Criteria) this;
        }

        public Criteria andGrapIdLessThanOrEqualTo(Integer value) {
            addCriterion("grap_id <=", value, "grapId");
            return (Criteria) this;
        }

        public Criteria andGrapIdIn(List<Integer> values) {
            addCriterion("grap_id in", values, "grapId");
            return (Criteria) this;
        }

        public Criteria andGrapIdNotIn(List<Integer> values) {
            addCriterion("grap_id not in", values, "grapId");
            return (Criteria) this;
        }

        public Criteria andGrapIdBetween(Integer value1, Integer value2) {
            addCriterion("grap_id between", value1, value2, "grapId");
            return (Criteria) this;
        }

        public Criteria andGrapIdNotBetween(Integer value1, Integer value2) {
            addCriterion("grap_id not between", value1, value2, "grapId");
            return (Criteria) this;
        }

        public Criteria andCommunityIdIsNull() {
            addCriterion("community_id is null");
            return (Criteria) this;
        }

        public Criteria andCommunityIdIsNotNull() {
            addCriterion("community_id is not null");
            return (Criteria) this;
        }

        public Criteria andCommunityIdEqualTo(Integer value) {
            addCriterion("community_id =", value, "communityId");
            return (Criteria) this;
        }

        public Criteria andCommunityIdNotEqualTo(Integer value) {
            addCriterion("community_id <>", value, "communityId");
            return (Criteria) this;
        }

        public Criteria andCommunityIdGreaterThan(Integer value) {
            addCriterion("community_id >", value, "communityId");
            return (Criteria) this;
        }

        public Criteria andCommunityIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("community_id >=", value, "communityId");
            return (Criteria) this;
        }

        public Criteria andCommunityIdLessThan(Integer value) {
            addCriterion("community_id <", value, "communityId");
            return (Criteria) this;
        }

        public Criteria andCommunityIdLessThanOrEqualTo(Integer value) {
            addCriterion("community_id <=", value, "communityId");
            return (Criteria) this;
        }

        public Criteria andCommunityIdIn(List<Integer> values) {
            addCriterion("community_id in", values, "communityId");
            return (Criteria) this;
        }

        public Criteria andCommunityIdNotIn(List<Integer> values) {
            addCriterion("community_id not in", values, "communityId");
            return (Criteria) this;
        }

        public Criteria andCommunityIdBetween(Integer value1, Integer value2) {
            addCriterion("community_id between", value1, value2, "communityId");
            return (Criteria) this;
        }

        public Criteria andCommunityIdNotBetween(Integer value1, Integer value2) {
            addCriterion("community_id not between", value1, value2, "communityId");
            return (Criteria) this;
        }

        public Criteria andActivityNameIsNull() {
            addCriterion("activity_name is null");
            return (Criteria) this;
        }

        public Criteria andActivityNameIsNotNull() {
            addCriterion("activity_name is not null");
            return (Criteria) this;
        }

        public Criteria andActivityNameEqualTo(String value) {
            addCriterion("activity_name =", value, "activityName");
            return (Criteria) this;
        }

        public Criteria andActivityNameNotEqualTo(String value) {
            addCriterion("activity_name <>", value, "activityName");
            return (Criteria) this;
        }

        public Criteria andActivityNameGreaterThan(String value) {
            addCriterion("activity_name >", value, "activityName");
            return (Criteria) this;
        }

        public Criteria andActivityNameGreaterThanOrEqualTo(String value) {
            addCriterion("activity_name >=", value, "activityName");
            return (Criteria) this;
        }

        public Criteria andActivityNameLessThan(String value) {
            addCriterion("activity_name <", value, "activityName");
            return (Criteria) this;
        }

        public Criteria andActivityNameLessThanOrEqualTo(String value) {
            addCriterion("activity_name <=", value, "activityName");
            return (Criteria) this;
        }

        public Criteria andActivityNameLike(String value) {
            addCriterion("activity_name like", value, "activityName");
            return (Criteria) this;
        }

        public Criteria andActivityNameNotLike(String value) {
            addCriterion("activity_name not like", value, "activityName");
            return (Criteria) this;
        }

        public Criteria andActivityNameIn(List<String> values) {
            addCriterion("activity_name in", values, "activityName");
            return (Criteria) this;
        }

        public Criteria andActivityNameNotIn(List<String> values) {
            addCriterion("activity_name not in", values, "activityName");
            return (Criteria) this;
        }

        public Criteria andActivityNameBetween(String value1, String value2) {
            addCriterion("activity_name between", value1, value2, "activityName");
            return (Criteria) this;
        }

        public Criteria andActivityNameNotBetween(String value1, String value2) {
            addCriterion("activity_name not between", value1, value2, "activityName");
            return (Criteria) this;
        }

        public Criteria andBeginTimeIsNull() {
            addCriterion("begin_time is null");
            return (Criteria) this;
        }

        public Criteria andBeginTimeIsNotNull() {
            addCriterion("begin_time is not null");
            return (Criteria) this;
        }

        public Criteria andBeginTimeEqualTo(Date value) {
            addCriterion("begin_time =", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeNotEqualTo(Date value) {
            addCriterion("begin_time <>", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeGreaterThan(Date value) {
            addCriterion("begin_time >", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("begin_time >=", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeLessThan(Date value) {
            addCriterion("begin_time <", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeLessThanOrEqualTo(Date value) {
            addCriterion("begin_time <=", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeIn(List<Date> values) {
            addCriterion("begin_time in", values, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeNotIn(List<Date> values) {
            addCriterion("begin_time not in", values, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeBetween(Date value1, Date value2) {
            addCriterion("begin_time between", value1, value2, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeNotBetween(Date value1, Date value2) {
            addCriterion("begin_time not between", value1, value2, "beginTime");
            return (Criteria) this;
        }

        public Criteria andActivityStartTimeIsNull() {
            addCriterion("activity_start_time is null");
            return (Criteria) this;
        }

        public Criteria andActivityStartTimeIsNotNull() {
            addCriterion("activity_start_time is not null");
            return (Criteria) this;
        }

        public Criteria andActivityStartTimeEqualTo(Date value) {
            addCriterion("activity_start_time =", value, "activityStartTime");
            return (Criteria) this;
        }

        public Criteria andActivityStartTimeNotEqualTo(Date value) {
            addCriterion("activity_start_time <>", value, "activityStartTime");
            return (Criteria) this;
        }

        public Criteria andActivityStartTimeGreaterThan(Date value) {
            addCriterion("activity_start_time >", value, "activityStartTime");
            return (Criteria) this;
        }

        public Criteria andActivityStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("activity_start_time >=", value, "activityStartTime");
            return (Criteria) this;
        }

        public Criteria andActivityStartTimeLessThan(Date value) {
            addCriterion("activity_start_time <", value, "activityStartTime");
            return (Criteria) this;
        }

        public Criteria andActivityStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("activity_start_time <=", value, "activityStartTime");
            return (Criteria) this;
        }

        public Criteria andActivityStartTimeIn(List<Date> values) {
            addCriterion("activity_start_time in", values, "activityStartTime");
            return (Criteria) this;
        }

        public Criteria andActivityStartTimeNotIn(List<Date> values) {
            addCriterion("activity_start_time not in", values, "activityStartTime");
            return (Criteria) this;
        }

        public Criteria andActivityStartTimeBetween(Date value1, Date value2) {
            addCriterion("activity_start_time between", value1, value2, "activityStartTime");
            return (Criteria) this;
        }

        public Criteria andActivityStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("activity_start_time not between", value1, value2, "activityStartTime");
            return (Criteria) this;
        }

        public Criteria andActivityTicketLevelIsNull() {
            addCriterion("activity_ticket_level is null");
            return (Criteria) this;
        }

        public Criteria andActivityTicketLevelIsNotNull() {
            addCriterion("activity_ticket_level is not null");
            return (Criteria) this;
        }

        public Criteria andActivityTicketLevelEqualTo(Integer value) {
            addCriterion("activity_ticket_level =", value, "activityTicketLevel");
            return (Criteria) this;
        }

        public Criteria andActivityTicketLevelNotEqualTo(Integer value) {
            addCriterion("activity_ticket_level <>", value, "activityTicketLevel");
            return (Criteria) this;
        }

        public Criteria andActivityTicketLevelGreaterThan(Integer value) {
            addCriterion("activity_ticket_level >", value, "activityTicketLevel");
            return (Criteria) this;
        }

        public Criteria andActivityTicketLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("activity_ticket_level >=", value, "activityTicketLevel");
            return (Criteria) this;
        }

        public Criteria andActivityTicketLevelLessThan(Integer value) {
            addCriterion("activity_ticket_level <", value, "activityTicketLevel");
            return (Criteria) this;
        }

        public Criteria andActivityTicketLevelLessThanOrEqualTo(Integer value) {
            addCriterion("activity_ticket_level <=", value, "activityTicketLevel");
            return (Criteria) this;
        }

        public Criteria andActivityTicketLevelIn(List<Integer> values) {
            addCriterion("activity_ticket_level in", values, "activityTicketLevel");
            return (Criteria) this;
        }

        public Criteria andActivityTicketLevelNotIn(List<Integer> values) {
            addCriterion("activity_ticket_level not in", values, "activityTicketLevel");
            return (Criteria) this;
        }

        public Criteria andActivityTicketLevelBetween(Integer value1, Integer value2) {
            addCriterion("activity_ticket_level between", value1, value2, "activityTicketLevel");
            return (Criteria) this;
        }

        public Criteria andActivityTicketLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("activity_ticket_level not between", value1, value2, "activityTicketLevel");
            return (Criteria) this;
        }

        public Criteria andActivityTicketIsNull() {
            addCriterion("activity_ticket is null");
            return (Criteria) this;
        }

        public Criteria andActivityTicketIsNotNull() {
            addCriterion("activity_ticket is not null");
            return (Criteria) this;
        }

        public Criteria andActivityTicketEqualTo(Integer value) {
            addCriterion("activity_ticket =", value, "activityTicket");
            return (Criteria) this;
        }

        public Criteria andActivityTicketNotEqualTo(Integer value) {
            addCriterion("activity_ticket <>", value, "activityTicket");
            return (Criteria) this;
        }

        public Criteria andActivityTicketGreaterThan(Integer value) {
            addCriterion("activity_ticket >", value, "activityTicket");
            return (Criteria) this;
        }

        public Criteria andActivityTicketGreaterThanOrEqualTo(Integer value) {
            addCriterion("activity_ticket >=", value, "activityTicket");
            return (Criteria) this;
        }

        public Criteria andActivityTicketLessThan(Integer value) {
            addCriterion("activity_ticket <", value, "activityTicket");
            return (Criteria) this;
        }

        public Criteria andActivityTicketLessThanOrEqualTo(Integer value) {
            addCriterion("activity_ticket <=", value, "activityTicket");
            return (Criteria) this;
        }

        public Criteria andActivityTicketIn(List<Integer> values) {
            addCriterion("activity_ticket in", values, "activityTicket");
            return (Criteria) this;
        }

        public Criteria andActivityTicketNotIn(List<Integer> values) {
            addCriterion("activity_ticket not in", values, "activityTicket");
            return (Criteria) this;
        }

        public Criteria andActivityTicketBetween(Integer value1, Integer value2) {
            addCriterion("activity_ticket between", value1, value2, "activityTicket");
            return (Criteria) this;
        }

        public Criteria andActivityTicketNotBetween(Integer value1, Integer value2) {
            addCriterion("activity_ticket not between", value1, value2, "activityTicket");
            return (Criteria) this;
        }

        public Criteria andActivityImageIsNull() {
            addCriterion("activity_image is null");
            return (Criteria) this;
        }

        public Criteria andActivityImageIsNotNull() {
            addCriterion("activity_image is not null");
            return (Criteria) this;
        }

        public Criteria andActivityImageEqualTo(String value) {
            addCriterion("activity_image =", value, "activityImage");
            return (Criteria) this;
        }

        public Criteria andActivityImageNotEqualTo(String value) {
            addCriterion("activity_image <>", value, "activityImage");
            return (Criteria) this;
        }

        public Criteria andActivityImageGreaterThan(String value) {
            addCriterion("activity_image >", value, "activityImage");
            return (Criteria) this;
        }

        public Criteria andActivityImageGreaterThanOrEqualTo(String value) {
            addCriterion("activity_image >=", value, "activityImage");
            return (Criteria) this;
        }

        public Criteria andActivityImageLessThan(String value) {
            addCriterion("activity_image <", value, "activityImage");
            return (Criteria) this;
        }

        public Criteria andActivityImageLessThanOrEqualTo(String value) {
            addCriterion("activity_image <=", value, "activityImage");
            return (Criteria) this;
        }

        public Criteria andActivityImageLike(String value) {
            addCriterion("activity_image like", value, "activityImage");
            return (Criteria) this;
        }

        public Criteria andActivityImageNotLike(String value) {
            addCriterion("activity_image not like", value, "activityImage");
            return (Criteria) this;
        }

        public Criteria andActivityImageIn(List<String> values) {
            addCriterion("activity_image in", values, "activityImage");
            return (Criteria) this;
        }

        public Criteria andActivityImageNotIn(List<String> values) {
            addCriterion("activity_image not in", values, "activityImage");
            return (Criteria) this;
        }

        public Criteria andActivityImageBetween(String value1, String value2) {
            addCriterion("activity_image between", value1, value2, "activityImage");
            return (Criteria) this;
        }

        public Criteria andActivityImageNotBetween(String value1, String value2) {
            addCriterion("activity_image not between", value1, value2, "activityImage");
            return (Criteria) this;
        }

        public Criteria andSignOutIsNull() {
            addCriterion("sign_out is null");
            return (Criteria) this;
        }

        public Criteria andSignOutIsNotNull() {
            addCriterion("sign_out is not null");
            return (Criteria) this;
        }

        public Criteria andSignOutEqualTo(Integer value) {
            addCriterion("sign_out =", value, "signOut");
            return (Criteria) this;
        }

        public Criteria andSignOutNotEqualTo(Integer value) {
            addCriterion("sign_out <>", value, "signOut");
            return (Criteria) this;
        }

        public Criteria andSignOutGreaterThan(Integer value) {
            addCriterion("sign_out >", value, "signOut");
            return (Criteria) this;
        }

        public Criteria andSignOutGreaterThanOrEqualTo(Integer value) {
            addCriterion("sign_out >=", value, "signOut");
            return (Criteria) this;
        }

        public Criteria andSignOutLessThan(Integer value) {
            addCriterion("sign_out <", value, "signOut");
            return (Criteria) this;
        }

        public Criteria andSignOutLessThanOrEqualTo(Integer value) {
            addCriterion("sign_out <=", value, "signOut");
            return (Criteria) this;
        }

        public Criteria andSignOutIn(List<Integer> values) {
            addCriterion("sign_out in", values, "signOut");
            return (Criteria) this;
        }

        public Criteria andSignOutNotIn(List<Integer> values) {
            addCriterion("sign_out not in", values, "signOut");
            return (Criteria) this;
        }

        public Criteria andSignOutBetween(Integer value1, Integer value2) {
            addCriterion("sign_out between", value1, value2, "signOut");
            return (Criteria) this;
        }

        public Criteria andSignOutNotBetween(Integer value1, Integer value2) {
            addCriterion("sign_out not between", value1, value2, "signOut");
            return (Criteria) this;
        }

        public Criteria andSignInIsNull() {
            addCriterion("sign_in is null");
            return (Criteria) this;
        }

        public Criteria andSignInIsNotNull() {
            addCriterion("sign_in is not null");
            return (Criteria) this;
        }

        public Criteria andSignInEqualTo(Integer value) {
            addCriterion("sign_in =", value, "signIn");
            return (Criteria) this;
        }

        public Criteria andSignInNotEqualTo(Integer value) {
            addCriterion("sign_in <>", value, "signIn");
            return (Criteria) this;
        }

        public Criteria andSignInGreaterThan(Integer value) {
            addCriterion("sign_in >", value, "signIn");
            return (Criteria) this;
        }

        public Criteria andSignInGreaterThanOrEqualTo(Integer value) {
            addCriterion("sign_in >=", value, "signIn");
            return (Criteria) this;
        }

        public Criteria andSignInLessThan(Integer value) {
            addCriterion("sign_in <", value, "signIn");
            return (Criteria) this;
        }

        public Criteria andSignInLessThanOrEqualTo(Integer value) {
            addCriterion("sign_in <=", value, "signIn");
            return (Criteria) this;
        }

        public Criteria andSignInIn(List<Integer> values) {
            addCriterion("sign_in in", values, "signIn");
            return (Criteria) this;
        }

        public Criteria andSignInNotIn(List<Integer> values) {
            addCriterion("sign_in not in", values, "signIn");
            return (Criteria) this;
        }

        public Criteria andSignInBetween(Integer value1, Integer value2) {
            addCriterion("sign_in between", value1, value2, "signIn");
            return (Criteria) this;
        }

        public Criteria andSignInNotBetween(Integer value1, Integer value2) {
            addCriterion("sign_in not between", value1, value2, "signIn");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Byte value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Byte value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Byte value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Byte value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Byte value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Byte> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Byte> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Byte value1, Byte value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andSignInImageIsNull() {
            addCriterion("sign_in_image is null");
            return (Criteria) this;
        }

        public Criteria andSignInImageIsNotNull() {
            addCriterion("sign_in_image is not null");
            return (Criteria) this;
        }

        public Criteria andSignInImageEqualTo(String value) {
            addCriterion("sign_in_image =", value, "signInImage");
            return (Criteria) this;
        }

        public Criteria andSignInImageNotEqualTo(String value) {
            addCriterion("sign_in_image <>", value, "signInImage");
            return (Criteria) this;
        }

        public Criteria andSignInImageGreaterThan(String value) {
            addCriterion("sign_in_image >", value, "signInImage");
            return (Criteria) this;
        }

        public Criteria andSignInImageGreaterThanOrEqualTo(String value) {
            addCriterion("sign_in_image >=", value, "signInImage");
            return (Criteria) this;
        }

        public Criteria andSignInImageLessThan(String value) {
            addCriterion("sign_in_image <", value, "signInImage");
            return (Criteria) this;
        }

        public Criteria andSignInImageLessThanOrEqualTo(String value) {
            addCriterion("sign_in_image <=", value, "signInImage");
            return (Criteria) this;
        }

        public Criteria andSignInImageLike(String value) {
            addCriterion("sign_in_image like", value, "signInImage");
            return (Criteria) this;
        }

        public Criteria andSignInImageNotLike(String value) {
            addCriterion("sign_in_image not like", value, "signInImage");
            return (Criteria) this;
        }

        public Criteria andSignInImageIn(List<String> values) {
            addCriterion("sign_in_image in", values, "signInImage");
            return (Criteria) this;
        }

        public Criteria andSignInImageNotIn(List<String> values) {
            addCriterion("sign_in_image not in", values, "signInImage");
            return (Criteria) this;
        }

        public Criteria andSignInImageBetween(String value1, String value2) {
            addCriterion("sign_in_image between", value1, value2, "signInImage");
            return (Criteria) this;
        }

        public Criteria andSignInImageNotBetween(String value1, String value2) {
            addCriterion("sign_in_image not between", value1, value2, "signInImage");
            return (Criteria) this;
        }

        public Criteria andSignOutImageIsNull() {
            addCriterion("sign_out_image is null");
            return (Criteria) this;
        }

        public Criteria andSignOutImageIsNotNull() {
            addCriterion("sign_out_image is not null");
            return (Criteria) this;
        }

        public Criteria andSignOutImageEqualTo(String value) {
            addCriterion("sign_out_image =", value, "signOutImage");
            return (Criteria) this;
        }

        public Criteria andSignOutImageNotEqualTo(String value) {
            addCriterion("sign_out_image <>", value, "signOutImage");
            return (Criteria) this;
        }

        public Criteria andSignOutImageGreaterThan(String value) {
            addCriterion("sign_out_image >", value, "signOutImage");
            return (Criteria) this;
        }

        public Criteria andSignOutImageGreaterThanOrEqualTo(String value) {
            addCriterion("sign_out_image >=", value, "signOutImage");
            return (Criteria) this;
        }

        public Criteria andSignOutImageLessThan(String value) {
            addCriterion("sign_out_image <", value, "signOutImage");
            return (Criteria) this;
        }

        public Criteria andSignOutImageLessThanOrEqualTo(String value) {
            addCriterion("sign_out_image <=", value, "signOutImage");
            return (Criteria) this;
        }

        public Criteria andSignOutImageLike(String value) {
            addCriterion("sign_out_image like", value, "signOutImage");
            return (Criteria) this;
        }

        public Criteria andSignOutImageNotLike(String value) {
            addCriterion("sign_out_image not like", value, "signOutImage");
            return (Criteria) this;
        }

        public Criteria andSignOutImageIn(List<String> values) {
            addCriterion("sign_out_image in", values, "signOutImage");
            return (Criteria) this;
        }

        public Criteria andSignOutImageNotIn(List<String> values) {
            addCriterion("sign_out_image not in", values, "signOutImage");
            return (Criteria) this;
        }

        public Criteria andSignOutImageBetween(String value1, String value2) {
            addCriterion("sign_out_image between", value1, value2, "signOutImage");
            return (Criteria) this;
        }

        public Criteria andSignOutImageNotBetween(String value1, String value2) {
            addCriterion("sign_out_image not between", value1, value2, "signOutImage");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table grabticket
     *
     * @mbg.generated do_not_delete_during_merge Wed Apr 29 19:44:01 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table grabticket
     *
     * @mbg.generated Wed Apr 29 19:44:01 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}