package com.sofency.ticket.pojo;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_id
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    private String studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.name
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.telephone
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.is_vote
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    private Byte isVote;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.activity_id
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    private Integer activityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.vote_stu_id
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    private String voteStuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.openId
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    private String openid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_id
     *
     * @return the value of student.student_id
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_id
     *
     * @param studentId the value for student.student_id
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId == null ? null : studentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.name
     *
     * @return the value of student.name
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.name
     *
     * @param name the value for student.name
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.telephone
     *
     * @return the value of student.telephone
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.telephone
     *
     * @param telephone the value for student.telephone
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.is_vote
     *
     * @return the value of student.is_vote
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    public Byte getIsVote() {
        return isVote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.is_vote
     *
     * @param isVote the value for student.is_vote
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    public void setIsVote(Byte isVote) {
        this.isVote = isVote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.activity_id
     *
     * @return the value of student.activity_id
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.activity_id
     *
     * @param activityId the value for student.activity_id
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.vote_stu_id
     *
     * @return the value of student.vote_stu_id
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    public String getVoteStuId() {
        return voteStuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.vote_stu_id
     *
     * @param voteStuId the value for student.vote_stu_id
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    public void setVoteStuId(String voteStuId) {
        this.voteStuId = voteStuId == null ? null : voteStuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.openId
     *
     * @return the value of student.openId
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.openId
     *
     * @param openid the value for student.openId
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }
}