package com.sofency.ticket.pojo;

public class Ticket extends TicketKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.is_sign_in
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    private Byte isSignIn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.is_sign_out
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    private Byte isSignOut;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.is_sign_in
     *
     * @return the value of ticket.is_sign_in
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    public Byte getIsSignIn() {
        return isSignIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.is_sign_in
     *
     * @param isSignIn the value for ticket.is_sign_in
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    public void setIsSignIn(Byte isSignIn) {
        this.isSignIn = isSignIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.is_sign_out
     *
     * @return the value of ticket.is_sign_out
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    public Byte getIsSignOut() {
        return isSignOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.is_sign_out
     *
     * @param isSignOut the value for ticket.is_sign_out
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    public void setIsSignOut(Byte isSignOut) {
        this.isSignOut = isSignOut;
    }
}