package com.sofency.ticket.pojo;

import java.util.ArrayList;
import java.util.List;

public class TicketExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ticket
     *
     * @mbg.generated Thu Apr 16 09:24:31 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ticket
     *
     * @mbg.generated Thu Apr 16 09:24:31 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ticket
     *
     * @mbg.generated Thu Apr 16 09:24:31 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbg.generated Thu Apr 16 09:24:31 CST 2020
     */
    public TicketExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbg.generated Thu Apr 16 09:24:31 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbg.generated Thu Apr 16 09:24:31 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbg.generated Thu Apr 16 09:24:31 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbg.generated Thu Apr 16 09:24:31 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbg.generated Thu Apr 16 09:24:31 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbg.generated Thu Apr 16 09:24:31 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbg.generated Thu Apr 16 09:24:31 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbg.generated Thu Apr 16 09:24:31 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbg.generated Thu Apr 16 09:24:31 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbg.generated Thu Apr 16 09:24:31 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ticket
     *
     * @mbg.generated Thu Apr 16 09:24:31 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andStuIdIsNull() {
            addCriterion("stu_id is null");
            return (Criteria) this;
        }

        public Criteria andStuIdIsNotNull() {
            addCriterion("stu_id is not null");
            return (Criteria) this;
        }

        public Criteria andStuIdEqualTo(String value) {
            addCriterion("stu_id =", value, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdNotEqualTo(String value) {
            addCriterion("stu_id <>", value, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdGreaterThan(String value) {
            addCriterion("stu_id >", value, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdGreaterThanOrEqualTo(String value) {
            addCriterion("stu_id >=", value, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdLessThan(String value) {
            addCriterion("stu_id <", value, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdLessThanOrEqualTo(String value) {
            addCriterion("stu_id <=", value, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdLike(String value) {
            addCriterion("stu_id like", value, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdNotLike(String value) {
            addCriterion("stu_id not like", value, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdIn(List<String> values) {
            addCriterion("stu_id in", values, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdNotIn(List<String> values) {
            addCriterion("stu_id not in", values, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdBetween(String value1, String value2) {
            addCriterion("stu_id between", value1, value2, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdNotBetween(String value1, String value2) {
            addCriterion("stu_id not between", value1, value2, "stuId");
            return (Criteria) this;
        }

        public Criteria andGrapIdIsNull() {
            addCriterion("grap_id is null");
            return (Criteria) this;
        }

        public Criteria andGrapIdIsNotNull() {
            addCriterion("grap_id is not null");
            return (Criteria) this;
        }

        public Criteria andGrapIdEqualTo(Integer value) {
            addCriterion("grap_id =", value, "grapId");
            return (Criteria) this;
        }

        public Criteria andGrapIdNotEqualTo(Integer value) {
            addCriterion("grap_id <>", value, "grapId");
            return (Criteria) this;
        }

        public Criteria andGrapIdGreaterThan(Integer value) {
            addCriterion("grap_id >", value, "grapId");
            return (Criteria) this;
        }

        public Criteria andGrapIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("grap_id >=", value, "grapId");
            return (Criteria) this;
        }

        public Criteria andGrapIdLessThan(Integer value) {
            addCriterion("grap_id <", value, "grapId");
            return (Criteria) this;
        }

        public Criteria andGrapIdLessThanOrEqualTo(Integer value) {
            addCriterion("grap_id <=", value, "grapId");
            return (Criteria) this;
        }

        public Criteria andGrapIdIn(List<Integer> values) {
            addCriterion("grap_id in", values, "grapId");
            return (Criteria) this;
        }

        public Criteria andGrapIdNotIn(List<Integer> values) {
            addCriterion("grap_id not in", values, "grapId");
            return (Criteria) this;
        }

        public Criteria andGrapIdBetween(Integer value1, Integer value2) {
            addCriterion("grap_id between", value1, value2, "grapId");
            return (Criteria) this;
        }

        public Criteria andGrapIdNotBetween(Integer value1, Integer value2) {
            addCriterion("grap_id not between", value1, value2, "grapId");
            return (Criteria) this;
        }

        public Criteria andIsSignInIsNull() {
            addCriterion("is_sign_in is null");
            return (Criteria) this;
        }

        public Criteria andIsSignInIsNotNull() {
            addCriterion("is_sign_in is not null");
            return (Criteria) this;
        }

        public Criteria andIsSignInEqualTo(Byte value) {
            addCriterion("is_sign_in =", value, "isSignIn");
            return (Criteria) this;
        }

        public Criteria andIsSignInNotEqualTo(Byte value) {
            addCriterion("is_sign_in <>", value, "isSignIn");
            return (Criteria) this;
        }

        public Criteria andIsSignInGreaterThan(Byte value) {
            addCriterion("is_sign_in >", value, "isSignIn");
            return (Criteria) this;
        }

        public Criteria andIsSignInGreaterThanOrEqualTo(Byte value) {
            addCriterion("is_sign_in >=", value, "isSignIn");
            return (Criteria) this;
        }

        public Criteria andIsSignInLessThan(Byte value) {
            addCriterion("is_sign_in <", value, "isSignIn");
            return (Criteria) this;
        }

        public Criteria andIsSignInLessThanOrEqualTo(Byte value) {
            addCriterion("is_sign_in <=", value, "isSignIn");
            return (Criteria) this;
        }

        public Criteria andIsSignInIn(List<Byte> values) {
            addCriterion("is_sign_in in", values, "isSignIn");
            return (Criteria) this;
        }

        public Criteria andIsSignInNotIn(List<Byte> values) {
            addCriterion("is_sign_in not in", values, "isSignIn");
            return (Criteria) this;
        }

        public Criteria andIsSignInBetween(Byte value1, Byte value2) {
            addCriterion("is_sign_in between", value1, value2, "isSignIn");
            return (Criteria) this;
        }

        public Criteria andIsSignInNotBetween(Byte value1, Byte value2) {
            addCriterion("is_sign_in not between", value1, value2, "isSignIn");
            return (Criteria) this;
        }

        public Criteria andIsSignOutIsNull() {
            addCriterion("is_sign_out is null");
            return (Criteria) this;
        }

        public Criteria andIsSignOutIsNotNull() {
            addCriterion("is_sign_out is not null");
            return (Criteria) this;
        }

        public Criteria andIsSignOutEqualTo(Byte value) {
            addCriterion("is_sign_out =", value, "isSignOut");
            return (Criteria) this;
        }

        public Criteria andIsSignOutNotEqualTo(Byte value) {
            addCriterion("is_sign_out <>", value, "isSignOut");
            return (Criteria) this;
        }

        public Criteria andIsSignOutGreaterThan(Byte value) {
            addCriterion("is_sign_out >", value, "isSignOut");
            return (Criteria) this;
        }

        public Criteria andIsSignOutGreaterThanOrEqualTo(Byte value) {
            addCriterion("is_sign_out >=", value, "isSignOut");
            return (Criteria) this;
        }

        public Criteria andIsSignOutLessThan(Byte value) {
            addCriterion("is_sign_out <", value, "isSignOut");
            return (Criteria) this;
        }

        public Criteria andIsSignOutLessThanOrEqualTo(Byte value) {
            addCriterion("is_sign_out <=", value, "isSignOut");
            return (Criteria) this;
        }

        public Criteria andIsSignOutIn(List<Byte> values) {
            addCriterion("is_sign_out in", values, "isSignOut");
            return (Criteria) this;
        }

        public Criteria andIsSignOutNotIn(List<Byte> values) {
            addCriterion("is_sign_out not in", values, "isSignOut");
            return (Criteria) this;
        }

        public Criteria andIsSignOutBetween(Byte value1, Byte value2) {
            addCriterion("is_sign_out between", value1, value2, "isSignOut");
            return (Criteria) this;
        }

        public Criteria andIsSignOutNotBetween(Byte value1, Byte value2) {
            addCriterion("is_sign_out not between", value1, value2, "isSignOut");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ticket
     *
     * @mbg.generated do_not_delete_during_merge Thu Apr 16 09:24:31 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ticket
     *
     * @mbg.generated Thu Apr 16 09:24:31 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}