package com.sofency.ticket.pojo;

import java.util.Date;

public class VoteTicket {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voteticket.activity_id
     *
     * @mbg.generated Sat May 02 17:49:30 CST 2020
     */
    private Integer activityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voteticket.activity_name
     *
     * @mbg.generated Sat May 02 17:49:30 CST 2020
     */
    private String activityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voteticket.community_id
     *
     * @mbg.generated Sat May 02 17:49:30 CST 2020
     */
    private Integer communityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voteticket.begin_time
     *
     * @mbg.generated Sat May 02 17:49:30 CST 2020
     */
    private Date beginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voteticket.end_time
     *
     * @mbg.generated Sat May 02 17:49:30 CST 2020
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voteticket.status
     *
     * @mbg.generated Sat May 02 17:49:30 CST 2020
     */
    private Byte status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voteticket.activity_id
     *
     * @return the value of voteticket.activity_id
     *
     * @mbg.generated Sat May 02 17:49:30 CST 2020
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voteticket.activity_id
     *
     * @param activityId the value for voteticket.activity_id
     *
     * @mbg.generated Sat May 02 17:49:30 CST 2020
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voteticket.activity_name
     *
     * @return the value of voteticket.activity_name
     *
     * @mbg.generated Sat May 02 17:49:30 CST 2020
     */
    public String getActivityName() {
        return activityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voteticket.activity_name
     *
     * @param activityName the value for voteticket.activity_name
     *
     * @mbg.generated Sat May 02 17:49:30 CST 2020
     */
    public void setActivityName(String activityName) {
        this.activityName = activityName == null ? null : activityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voteticket.community_id
     *
     * @return the value of voteticket.community_id
     *
     * @mbg.generated Sat May 02 17:49:30 CST 2020
     */
    public Integer getCommunityId() {
        return communityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voteticket.community_id
     *
     * @param communityId the value for voteticket.community_id
     *
     * @mbg.generated Sat May 02 17:49:30 CST 2020
     */
    public void setCommunityId(Integer communityId) {
        this.communityId = communityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voteticket.begin_time
     *
     * @return the value of voteticket.begin_time
     *
     * @mbg.generated Sat May 02 17:49:30 CST 2020
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voteticket.begin_time
     *
     * @param beginTime the value for voteticket.begin_time
     *
     * @mbg.generated Sat May 02 17:49:30 CST 2020
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voteticket.end_time
     *
     * @return the value of voteticket.end_time
     *
     * @mbg.generated Sat May 02 17:49:30 CST 2020
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voteticket.end_time
     *
     * @param endTime the value for voteticket.end_time
     *
     * @mbg.generated Sat May 02 17:49:30 CST 2020
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voteticket.status
     *
     * @return the value of voteticket.status
     *
     * @mbg.generated Sat May 02 17:49:30 CST 2020
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voteticket.status
     *
     * @param status the value for voteticket.status
     *
     * @mbg.generated Sat May 02 17:49:30 CST 2020
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}