package com.sofency.ticket.pojo;

public class VoteTicketKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voteticket.activity_id
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    private Integer activityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voteticket.community_id
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    private Integer communityId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voteticket.activity_id
     *
     * @return the value of voteticket.activity_id
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voteticket.activity_id
     *
     * @param activityId the value for voteticket.activity_id
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voteticket.community_id
     *
     * @return the value of voteticket.community_id
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    public Integer getCommunityId() {
        return communityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voteticket.community_id
     *
     * @param communityId the value for voteticket.community_id
     *
     * @mbg.generated Sun Apr 19 08:40:26 CST 2020
     */
    public void setCommunityId(Integer communityId) {
        this.communityId = communityId;
    }
}