package com.sofency.ticket.mapper;

import com.sofency.ticket.pojo.VoteStudent;
import com.sofency.ticket.pojo.VoteStudentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface VoteStudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votestudent
     *
     * @mbg.generated Sun May 03 12:20:24 CST 2020
     */
    long countByExample(VoteStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votestudent
     *
     * @mbg.generated Sun May 03 12:20:24 CST 2020
     */
    int deleteByExample(VoteStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votestudent
     *
     * @mbg.generated Sun May 03 12:20:24 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votestudent
     *
     * @mbg.generated Sun May 03 12:20:24 CST 2020
     */
    int insert(VoteStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votestudent
     *
     * @mbg.generated Sun May 03 12:20:24 CST 2020
     */
    int insertSelective(VoteStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votestudent
     *
     * @mbg.generated Sun May 03 12:20:24 CST 2020
     */
    List<VoteStudent> selectByExampleWithRowbounds(VoteStudentExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votestudent
     *
     * @mbg.generated Sun May 03 12:20:24 CST 2020
     */
    List<VoteStudent> selectByExample(VoteStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votestudent
     *
     * @mbg.generated Sun May 03 12:20:24 CST 2020
     */
    VoteStudent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votestudent
     *
     * @mbg.generated Sun May 03 12:20:24 CST 2020
     */
    int updateByExampleSelective(@Param("record") VoteStudent record, @Param("example") VoteStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votestudent
     *
     * @mbg.generated Sun May 03 12:20:24 CST 2020
     */
    int updateByExample(@Param("record") VoteStudent record, @Param("example") VoteStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votestudent
     *
     * @mbg.generated Sun May 03 12:20:24 CST 2020
     */
    int updateByPrimaryKeySelective(VoteStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votestudent
     *
     * @mbg.generated Sun May 03 12:20:24 CST 2020
     */
    int updateByPrimaryKey(VoteStudent record);
}